### ISSUE TITLE
1.8 testing branch: Options > Mods button crashes the game if clicked outside of title screen

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1698]
```
--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v1.8 alpha / 0.13.0 (mod API)
sess. ID:	dicey_dungeons_2020-05-23_15'04'17
started:	2020-05-23 15:04:17
--------------------------------------
crashed:	2020-05-23 15:04:29
duration:	00:00:12
error:		ERROR in callscenemethod(DoYouWantToContinue,update) static : Null Object Reference, stack = 
Called from states.Title.decompose (states/Title.hx line 495)
Called from states.Title.changescene (states/Title.hx line 506)
Called from states.SettingsOptions.update (states/SettingsOptions.hx line 66)
Called from FadeControl.update (FadeControl.hx line 78)
Called from Screen.endrender (Screen.hx line 305)
Called from states.DoYouWantToContinue.update (states/DoYouWantToContinue.hx line 71)
Called from Reflect.callMethod (C:\coding\haxe\openfl\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 268)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)
```

**Comment by TerryCavanagh** [comment]
Fixed! This was an easy one - the Mods button isn't actually meant to appear unless you're actually on the title screen - we forgot to enforce that check when we changed the title screen for v1.8.

**Comment by shymu** [comment]
I'm on 1.8.2 (MacOS / Steam Version) and I still see a MODS button in-game and it still crashes my game.

Pic: 
<img width="1392" alt="Screen Shot 2020-07-11 at 9 52 53 AM" src="https://user-images.githubusercontent.com/38837724/87225611-6c52e180-c35c-11ea-86fa-741366e5619a.png">

**Comment by Matz-42** [comment]
@shymu Pretty sure by "fixed" terry means fixed in the upcoming update (1.9)
So don't worry you still getting it is normal.
