### ISSUE TITLE
Trading Post should check not to offer you the same thing you're trading

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#586]
![unknown](https://user-images.githubusercontent.com/2874150/46916409-5e6b0380-cfb2-11e8-8f8f-9f581f7e630e.png)

**Comment by TerryCavanagh** [comment]
Fixed.

**Comment by XenethDesign** [comment]
This can still occur as of v2.1 if you’re doing the warrior  episode where all equipment is upgraded!

![97A2C0DF-B3B7-4531-97D6-A888F8EDD1C9](https://user-images.githubusercontent.com/18407623/191100996-ede5967b-e3a6-4c49-8639-b48be2f75be4.png)
